name: fase
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - git
  - sox
  - pip:
    - git+https://github.com/rsprouse/audiolabel
    - git+https://github.com/EricWilbanks/faseAlign.git

